name: BladeOfGreed
version: 1.0.0
main: me.greed.bladeofgreed.BladeOfGreedPlugin

description: BladeOfGreed Paper plugin
author: c5kua0

api-version: '26.1'

commands:
  greed:
    description: Main BladeOfGreed command
    usage: /greed
    permission: bladeofgreed.use

permissions:
  bladeofgreed.use:
    description: Allows use of BladeOfGreed commands
    default: true