name: BladeOfGreed
version: 1.0.0
main: me.greed.bladeofgreed.BladeOfGreedPlugin

description: BladeOfGreed
author: TUKOSHIBU

api-version: '26.1'

commands:
  bg:
    description: Main BladeOfGreed command
    usage: /bg
    permission: bladeofgreed.use

permissions:
  bladeofgreed.use:
    description: Allows use of BladeOfGreed commands
    default: true